// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgradeUserbyID.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upgradeUserByID = `-- name: UpgradeUserByID :one
UPDATE users
SET is_chirpy_red = true
WHERE id = $1

returning id, created_at, updated_at, email, is_chirpy_red
`

type UpgradeUserByIDRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	IsChirpyRed bool
}

func (q *Queries) UpgradeUserByID(ctx context.Context, id uuid.UUID) (UpgradeUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserByID, id)
	var i UpgradeUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}
